galaxy_info:
  author: Mehran Asghari
  description: Deploy GitHub Actions runner
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []